### ISSUE TITLE
Refused to set unsafe header "Content-length" and "Connection"

### ISSUE THREAD

**Issue by epigeyre** [Hube2/blunt-ajax#5]
Hello,

Thanks for your plugin! I'm actualy playing with it to see if it fits my project. The plugin is working great but I get two errors in the console : `Refused to set unsafe header "Content-length"` and `Refused to set unsafe header "Connection"`.

After further research, I've found that it is best practice not to set `"Content-length"` and `"Connection"` headers so I've removed the following lines in the `blunt-ajax` script (lines 259 and 260) :

```
xmlHttp.setRequestHeader("Content-length", post_args.length);
xmlHttp.setRequestHeader("Connection", "close");
```

I thought you'd be interested to improve your script. Anyway, thanks a lot for your work!

**Comment by Hube2** [comment]
I've removed the lines causing these warnings, everything seems to be working without them. They were probably required when I first built this thing. Let me know if you see any other problems.
